# .github/workflows/main-cicd.yml
name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
      - dev
      - staging
  push:
    branches:
      - main
      - dev
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  call-dev:
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'push' && github.ref == 'refs/heads/main' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    uses: ./.github/workflows/terraform-job.yml
    with:
      environment: dev
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  # call-staging:
  #   if: |
  #     github.event_name == 'pull_request' && github.base_ref == 'staging' ||
  #     github.event_name == 'push' && github.ref == 'refs/heads/staging' ||
  #     (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
  #   uses: ./.github/workflows/terraform-job.yml
  #   with:
  #     environment: staging
  #   secrets:
  #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  # call-prod:
  #   if: |
  #     github.event_name == 'pull_request' && github.base_ref == 'main' ||
  #     github.event_name == 'push' && github.ref == 'refs/heads/main' ||
  #     (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
  #   uses: ./.github/workflows/terraform-job.yml
  #   with:
  #     environment: prod
  #   secrets:
  #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
