# .github/workflows/terraform-job.yml
name: Reusable Terraform Job

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      GCP_SA_KEY:
        required: true
      GCP_PROJECT_ID:
        required: true

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        shell: bash

    env:
      TF_VERSION: 1.7.5
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup GCP Credentials
        run: |
          echo "$GOOGLE_CREDENTIALS" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project "$PROJECT_ID"
      
      - name: Write backend.tfvars
        run: |
          sed "s|credentials = .*|credentials = \"/tmp/gcp-key.json\"|" ./environments/${{ inputs.environment }}/backend.tfvars > /tmp/backend.tfvars
      
      - name: Terraform Init
        working-directory: ./environments/${{ inputs.environment }}
        run: terraform init -backend-config=/tmp/backend.tfvars
      
      - name: Terraform Validate
        working-directory: ./environments/${{ inputs.environment }}
        run: terraform validate
      
      - name: Terraform Plan
        working-directory: ./environments/${{ inputs.environment }}
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform Apply
        working-directory: ./environments/${{ inputs.environment }}
        if: |
          github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan
